### ISSUE TITLE
How to run the plug-in?

### ISSUE THREAD

**Issue by richardeigenmann** [aoloe/scribus-plugin-export-epub#10]
I've compiled scribus with the module symlinked in the source code as described in the README. But where will I find the Export to EPUB in the scribus menus? EPUB doesn't show up in the File > Export menu. Should it? Or do we have to run a command to convert a document? Which one? Please add this to the Readme.

**Comment by aoloe** [comment]
yes, it should be added as "file > export > save as epub" in the menu...

is it listed in "file > preferences > plugins"?

**Comment by richardeigenmann** [comment]
If it should be called EPUB Exporter then no, it is not present in the Plug-ins Preferences page. I do see a PUB importer. It looks like the compile of scribus ignores my symlinked epub directory in /home/user/scribus/scribus/plugins/export (which is the src directory of the plug in scribus-plugin-export-epub) I have also copied the src directory locally to avoid symlink issues but it doesn't get picked up.

**Comment by aoloe** [comment]
it's called "Epub Export".

hard to say what is happening.

a few ideas:

- you could try to change the plugin's code with an obvious error and see if it get compiled (did you add it to the `lugins/export/CMakeLists.txt? file? 
- do not forget to `make install`
- make sure that you're starting the scribus that you have make installed.

**Comment by richardeigenmann** [comment]
OK. My Bad: I didn't RTFM properly. I would suggest adding the lines to the Install section:

 ```bash
cd to/your/top/src/directory
git clone https://github.com/aoloe/scribus-plugin-API.git
git clone https://github.com/aoloe/scribus-plugin-export-epub.git

# connect the scribus-plugin-API with the scribus build
cd scribus/scribus/plugin
ln -s ../../../scribus-plugin-API/src scribus-plugin-API
echo "ADD_SUBDIRECTORY(scribusAPI)" >> CMakesLists.txt

# connect the scribus-plugin-export-epub to the scribus build
cd export  # i.e. scribus/scribus/plugin/export
ln -s ../../../../scribus-plugin-export-epub/src epub
echo "ADD_SUBDIRECTORY(epub)" >> CMakesLists.txt

# now compile scribus
cd ../../../build
cmake ..
make
sudo make install
```

**Comment by aoloe** [comment]
perfect!

i've enhanced the "getting started" for developer manual and put a link in each plugin's readme file:

723529860d2648a5e2e7b827d5c5a5ea6b3a2f0
